export const ErrorCodes = {
  SPAWN_FAILED: 'SPAWN_FAILED',
  FILE_READ_ERROR: 'FILE_READ_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  INSTALL_FAILED: 'INSTALL_FAILED',
  SCORE_FAILED: 'SCORE_FAILED',
  AUTH_FAILED: 'AUTH_FAILED',
  PUBLISH_BLOCKED: 'PUBLISH_BLOCKED',
} as const;
